config/routes.rb
Clipmeme::Application.routes.draw do
  resources :video_clips

  root :to => 'index#index'

end

app/models/video_clip.rb
class VideoClip
  include Mongoid::Document
  field :name, :type => String
  field :youtube_video_id, :type => String
  field :start_seconds, :type => Float
  field :end_seconds, :type => Float
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @video_clips = VideoClip.all
  end
end

app/controllers/video_clips_controller.rb
class VideoClipsController < ApplicationController
  # GET /video_clips
  # GET /video_clips.json
  def index
    @video_clips = VideoClip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @video_clips }
    end
  end

  # GET /video_clips/1
  # GET /video_clips/1.json
  def show
    @video_clip = VideoClip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video_clip }
    end
  end

  # GET /video_clips/new
  # GET /video_clips/new.json
  def new
    @video_clip = VideoClip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video_clip }
    end
  end

  # GET /video_clips/1/edit
  def edit
    @video_clip = VideoClip.find(params[:id])
  end

  # POST /video_clips
  # POST /video_clips.json
  def create
    @video_clip = VideoClip.new(params[:video_clip])

    respond_to do |format|
      if @video_clip.save
        format.html { redirect_to @video_clip, notice: 'Video clip was successfully created.' }
        format.json { render json: @video_clip, status: :created, location: @video_clip }
      else
        format.html { render action: "new" }
        format.json { render json: @video_clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /video_clips/1
  # PUT /video_clips/1.json
  def update
    @video_clip = VideoClip.find(params[:id])

    respond_to do |format|
      if @video_clip.update_attributes(params[:video_clip])
        format.html { redirect_to @video_clip, notice: 'Video clip was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @video_clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_clips/1
  # DELETE /video_clips/1.json
  def destroy
    @video_clip = VideoClip.find(params[:id])
    @video_clip.destroy

    respond_to do |format|
      format.html { redirect_to video_clips_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_controller_helper.rb
module IndexControllerHelper
end

app/helpers/video_clips_helper.rb
module VideoClipsHelper
end

app/views/index/index.html.haml
:javascript
  videoClips = new Clipmeme.Collections.VideoClipsCollection( #{ @video_clips.to_json } )

app/views/layouts/application.html.haml
%html
%head
  %title Clipmeme
  = stylesheet_link_tag    "application"
  = javascript_include_tag "application"
  = csrf_meta_tags
  %script{src:"http://www.google.com/jsapi", type:"text/javascript"}
  %script{type:"text/javascript"}
    google.load("swfobject", "2.1");

%body
  = yield

app/views/video_clips/_form.html.haml
= form_for @video_clip do |f|
  -if @video_clip.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video_clip.errors.count, "error")} prohibited this video_clip from being saved:"
      %ul
        - @video_clip.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :youtube_video_id
    = f.text_field :youtube_video_id
  .field
    = f.label :start_seconds
    = f.text_field :start_seconds
  .field
    = f.label :end_seconds
    = f.text_field :end_seconds
  .actions
    = f.submit 'Save'

app/views/video_clips/edit.html.haml
%h1 Editing video_clip

= render 'form'

= link_to 'Show', @video_clip
\|
= link_to 'Back', video_clips_path

app/views/video_clips/index.html.haml
%h1 Listing video_clips

%table
  %tr
    %th Name
    %th Video
    %th Start seconds
    %th End seconds
    %th
    %th
    %th

  - @video_clips.each do |video_clip|
    %tr
      %td= video_clip.name
      %td= video_clip.youtube_video_id
      %td= video_clip.start_seconds
      %td= video_clip.end_seconds
      %td= link_to 'Show', video_clip
      %td= link_to 'Edit', edit_video_clip_path(video_clip)
      %td= link_to 'Destroy', video_clip, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Video clip', new_video_clip_path

app/views/video_clips/new.html.haml
%h1 New video_clip

= render 'form'

= link_to 'Back', video_clips_path

app/views/video_clips/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @video_clip.name
%p
  %b Video:
  = @video_clip.youtube_video_id
%p
  %b Start seconds:
  = @video_clip.start_seconds
%p
  %b End seconds:
  = @video_clip.end_seconds

= link_to 'Edit', edit_video_clip_path(@video_clip)
\|
= link_to 'Back', video_clips_path